### ISSUE TITLE
Got [Warning]: Failed to resolved /home/owner/share/tmp/sdk_tools/Wits

### ISSUE THREAD

**Issue by ys2843** [Samsung/Wits#14]
Set up everything and launched WTIs, but in the browser WITs stay Disconnected and at the console I see these messages:

------

main.js:37 onload!!!
main.js:142 reqAppControl.appControl.data
main.js:143 Array(4)
main.js:58 [Warning]: Failed to resolved /home/owner/share/tmp/sdk_tools/Wits
172.28.195.69:8498/socket.io/?EIO=3&transport=polling&t=1555365479786-0 
Failed to load resource: net::ERR_TIMED_OUT

**Comment by pwsses** [comment]
Hello.
This issue is from failed to socket connect. Wits try to connect TV and PC with socket.io lib. But It is failed. Please check your network env.
Additionally, warning message is not an issue because Wits try to remove previous your app code at launch. At first time, your app does not exist so Wits showing warning message.
Thank you for your interest.
