### ISSUE TITLE
Problem when starting a new project

### ISSUE THREAD

**Issue by Guidogl** [Samsung/Wits#35]
Hi,

When I type `wits --start` project build is successful, however I get a message - `Total File Number : 7415` and project loads for quite a while but after it finishes loading, it shows this error on TV:

![20200521_131222](https://user-images.githubusercontent.com/6173458/82549070-066c8980-9b65-11ea-9d95-724cb5f1f7e6.jpg)

In Google Chrome I get the following error: 

![wits_console](https://user-images.githubusercontent.com/6173458/82548382-e5576900-9b63-11ea-9916-ef5cb9cf0556.PNG)

My guess is that it loads files from previous project because I tried Wits half a year ago. Is that possible?

Do I need to place my build file to www folder as before? I can't find any information about that part.

**Comment by prozanne** [comment]
Hi, It looks like a compatibility issue on WITs.
WITs(v2.0.0) was updated since 26th March, 2020.
And for sure the manual was updated.
If you use WITs(v1.0.0), you can use "www" folders just like before.
https://github.com/Samsung/Wits/releases/tag/v1.0.0

So just download locally and you can use it.

Or if you want to try New WITs(v2.0.0),
You can remove previous WITs, and just install

1. npm install -g @tizentv/wits
2. You can just run WITs inside your project regardless where real WITs is located.

WITs (v2.0.0)
1. Go to your project root
2. wits --init (for setting configuration to use WITs - this step is neccessary to run WITs)
3. After .witignore is created, you need to add useless files (ex. node_modules)
4. wits --start (for packaging and connecting, installing your project to device)

After once you install your project, you can just use "wits --watch" without reinstall your project on device.

You can try above solutions for resolving this issue.
If you can't use WITs after trying these ways, let me know again.

**Comment by Guidogl** [comment]
Hi, now I did what you wrote and wits found over 35000 files to upload to TV. Where it is looking for files? I initiated wits in project root and added unnecessary files to .witignore.

**Comment by prozanne** [comment]
WITs is looking for files in the project root itself.
Can you share the .witsignore file?

**Comment by prozanne** [comment]
If it is contained "/", change just like this.
"node_modules/" => "node_modules"

**Comment by Guidogl** [comment]
yes, it works after removing "/" and I had to setup wits in my build folder. 

But the problem with chrome debugger still persist. I am getting the below error in console 

![chrome](https://user-images.githubusercontent.com/6173458/82663463-66803000-9c38-11ea-9124-dda32ddb7e5c.PNG)

After I click on Wits hyperling the error changes to this: 

![wits_console](https://user-images.githubusercontent.com/6173458/82663522-7ef04a80-9c38-11ea-9813-209f703cfbc8.PNG)

Can you help with that?

**Comment by prozanne** [comment]
Hi, so you mean you managed to install application on Device via WITs, but the inspector had an error like that?
If you don't mind, can you share your archived project? Then I will take a look.

**Comment by prozanne** [comment]
Hi, If only the inspector is a problem, It could be the issue of the Chrome version. If you use the Chrome over version 80, the inspector is not working properly. If you download the Chrome under 80 version, then probably you can use it.

**Comment by Guidogl** [comment]
Hi, it works with Chrome version 79. 

Thanks
