### ISSUE TITLE
Need more instructions

### ISSUE THREAD

**Issue by Hisagr** [Samsung/Wits#7]
Hello,

I am confused about how Wits is supposed to work.  

I followed the instructions and launched Wits on my Smart TV. It copied my project files and it just stays on loading 100%. In the terminal, I see that it watches for the file changes and it stops if I minimize the app on the TV. 

And that's it so far. I'm not sure how this is equivalent to building -> packaging -> reinstalling. I think I must be missing something. 

Right now, I'm using Toast plugin with some custom scripts to rebuild and launch the app on TV in one command. The Wits idea sounds really cool and I'd like to try it out.

Thanks for your help!

**Comment by pwsses** [comment]
Hi
Thank you for your time and consideration.

As your review, Wits stop watches when the application is minimized.
But when you restart app on TV, Wits also start watches your app if the nodeJS is live.

If you need any help, please contact to Wits.

I hope that Wits project help to you.

Thank you.

**Comment by Hisagr** [comment]
Hi,

Thanks for your reply.

Sorry, I think you misunderstood my question. I'll try to clarify what I meant:

I have the Wits app opened on my TV and I have node running in my localhost. It's watching for changes in the directory I specified, no issues with that. 

**My questions are:**

- What's next? How do I see the changes I made in files being reflected in my app?

- Is it supposed to rebuild the package automatically after each change?

- How my project files that have been copied on TV by Wits are converted to the app that I can run (alternately to what I do right now -> tizen run -t device -p packageID.AppName)

Thanks again for your help, it's much appreciated!

**Comment by pwsses** [comment]
Hi,

Sorry to late reply.

I answer your questions.

* If you changes your file, you can see in your app on TV. When you changed something, Wits refresh with new file. and you can see that.

* It is not supported yet. I think, If Wits will support rebuild after each change, it would be inefficient. 
  Instead of I will may be make a new command which app build and package.

* As your review, currently Wits is wrapped your app. so if you run app with command, you should use Wits package ID (UQFmc9jZyO.Wits). I have plan improvement it.

Thank you very much your detail review.
